CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    username VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    details VARCHAR(1000)
);

CREATE INDEX idx_evidence_user_id ON evidence(user_id);
CREATE INDEX idx_evidence_status ON evidence(status);
CREATE INDEX idx_evidence_type ON evidence(type);
CREATE INDEX idx_evidence_date_collected ON evidence(date_collected);
CREATE INDEX idx_audit_log_username ON audit_log(username);
